name: Build Thinkpad Assistant

on:
  pull_request:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  CI:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Prepare Env
        run: |
          pod install

      - name: Debug Build
        run: xcodebuild -workspace ThinkpadAssistant.xcworkspace -scheme ThinkpadAssistant -destination "platform=macOS" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
